# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

[Assignment link](https://raw.githubusercontent.com/mrdbourke/zero-to-mastery-ml/refs/heads/master/section-2-data-science-and-ml-tools/numpy-exercises.ipynb)

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [2]:
# Create a 1-dimensional NumPy array using np.array()
a1 = np.array([1,3,4])

# Create a 2-dimensional NumPy array using np.array()
a2 = np.array([[1,53,15],[2,4,1]])

# Create a 3-dimensional Numpy array using np.array()
a3 = np.array([[[1,2,7],[3,4,0]],[[2,8,3],[6,5,1]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [3]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
a1.ndim, a1.dtype, a1.size, type(a1)

(1, dtype('int32'), 3, numpy.ndarray)

In [4]:
# Attributes of 2-dimensional array
a2.ndim, a2.dtype

(2, dtype('int32'))

In [5]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
df = pd.DataFrame(a2)
df

0   1   2
0  1  53  15
1  2   4   1

In [6]:
# Create an array of shape (10, 2) with only ones
np.ones(shape=(10,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [7]:
# Create an array of shape (7, 2, 3) of only zeros
np.zeros(shape=(7,2,3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [8]:
# Create an array within a range of 0 and 100 with step 3
np.arange(0,100,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [9]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
np.random.randint(0,10,size=(7,2))

array([[2, 9],
       [2, 9],
       [6, 8],
       [3, 6],
       [5, 7],
       [3, 9],
       [6, 8]])

In [10]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
np.random.random(size=(3,5))

array([[0.71889278, 0.78539692, 0.43173077, 0.45007039, 0.0675419 ],
       [0.90851547, 0.90676151, 0.05540643, 0.18035386, 0.58371863],
       [0.9710265 , 0.15443122, 0.7794301 , 0.67189588, 0.27414229]])

In [11]:
# Set the random seed to 42

np.random.seed(42)
# Create a random array of numbers between 0 & 10 of size (4, 6)
np.random.randint(0,10, size=(4,6))

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [12]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable

arr = np.random.randint(1,10,size=(3,7))
# Find the unique numbers in the array you just created
arr, np.unique(arr)

(array([[9, 1, 3, 7, 4, 9, 3],
        [5, 3, 7, 5, 9, 7, 2],
        [4, 9, 2, 9, 5, 2, 4]]),
 array([1, 2, 3, 4, 5, 7, 9]))

In [13]:
# Find the 0'th index of the latest array you created
arr.flatten()[0]

9

In [14]:
# Get the first 2 rows of latest array you created
arr[:2]

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2]])

In [15]:
# Get the first 2 values of the first 2 rows of the latest array
arr[:2,:2]

array([[9, 1],
       [5, 3]])

In [16]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
ones = np.ones(shape=(3,5))
arr1 = np.random.randint(0,10, size=(3,5))
ones,arr1

(array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]),
 array([[6, 7, 2, 0, 3],
        [1, 7, 3, 1, 5],
        [5, 9, 3, 5, 1]]))

In [17]:
# Add the two arrays together
ones+arr1

array([[ 7.,  8.,  3.,  1.,  4.],
       [ 2.,  8.,  4.,  2.,  6.],
       [ 6., 10.,  4.,  6.,  2.]])

In [18]:
# Create another array of ones of shape (5, 3)
arr2 = np.random.randint(0,10, size=(5,3))

In [19]:
# Try add the array of ones and the other most recent array together
arr2+ones

ValueError: operands could not be broadcast together with shapes (5,3) (3,5) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [125]:
# Create another array of ones of shape (3, 5)
arr2+ones.T

array([[ 1.,  8.,  1.],
       [ 1.,  2.,  2.],
       [ 6.,  7.,  5.],
       [ 1.,  1.,  3.],
       [ 2.,  5., 10.]])

In [126]:
# Subtract the new array of ones from the other most recent array
ones-arr1

array([[-8., -6., -4., -6., -7.],
       [-2.,  1.,  1., -8., -2.],
       [-5.,  0., -1.,  1., -3.]])

In [128]:
# Multiply the ones array with the latest array
ones.T * arr2

array([[0., 7., 0.],
       [0., 1., 1.],
       [5., 6., 4.],
       [0., 0., 2.],
       [1., 4., 9.]])

In [ ]:
# Take the latest array to the power of 2 using '**'
np.power(arr2, 2), arr2**2

(array([[ 0, 49,  0],
        [ 0,  1,  1],
        [25, 36, 16],
        [ 0,  0,  4],
        [ 1, 16, 81]], dtype=int32),
 array([[ 0, 49,  0],
        [ 0,  1,  1],
        [25, 36, 16],
        [ 0,  0,  4],
        [ 1, 16, 81]]))

In [131]:
# Do the same thing with np.square()
np.square(arr2)

array([[ 0, 49,  0],
       [ 0,  1,  1],
       [25, 36, 16],
       [ 0,  0,  4],
       [ 1, 16, 81]])

In [132]:
# Find the mean of the latest array using np.mean()
np.mean(arr2)

2.6666666666666665

In [133]:
# Find the maximum of the latest array using np.max()
np.max(arr2)

9

In [134]:
# Find the minimum of the latest array using np.min()
np.min(arr2)

0

In [135]:
# Find the standard deviation of the latest array
np.std(arr2)

2.8674417556808756

In [136]:
# Find the variance of the latest array
np.var(arr2)

8.222222222222223

In [155]:
# Reshape the latest array to (3, 5, 1)
arr2 = arr2.reshape(3,5,1)
arr2

array([[[0],
        [7],
        [0],
        [0],
        [1]],

       [[1],
        [5],
        [6],
        [4],
        [0]],

       [[0],
        [2],
        [1],
        [4],
        [9]]])

In [156]:
# Transpose the latest array
arr2.T

array([[[0, 1, 0],
        [7, 5, 2],
        [0, 6, 1],
        [0, 4, 4],
        [1, 0, 9]]])

What does the transpose do?

In [157]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
arr3 = np.random.randint(1,10, size=(3,3))
arr4 = np.random.randint(1, 10, size=(3, 2))
arr3, arr4

(array([[6, 7, 4],
        [7, 8, 1],
        [6, 8, 5]]),
 array([[4, 2],
        [6, 6],
        [1, 9]]))

In [158]:
# Perform a dot product on the two newest arrays you created
np.dot(arr3, arr4)

array([[ 70,  90],
       [ 77,  71],
       [ 77, 105]])

In [159]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
arr5 = np.random.randint(0,10, size=(4,3))
arr6 = np.random.randint(0, 10, size=(4, 3))
arr5,arr6

(array([[5, 2, 3],
        [3, 2, 9],
        [2, 2, 3],
        [6, 3, 8]]),
 array([[0, 7, 6],
        [1, 7, 0],
        [8, 8, 1],
        [6, 9, 2]]))

In [160]:
# Perform a dot product on the two newest arrays you created
np.dot(arr5, arr6)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [161]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
np.dot(arr5, arr6.T)

array([[32, 19, 59, 54],
       [68, 17, 49, 54],
       [32, 16, 35, 36],
       [69, 27, 80, 79]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [163]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
arr7 = np.random.randint(0,10, size=(3,4))
arr8 = np.random.randint(0, 10, size=(3, 4))
arr7, arr8

(array([[3, 5, 7, 3],
        [2, 8, 2, 8],
        [1, 1, 1, 5]]),
 array([[2, 8, 3, 0],
        [3, 0, 4, 3],
        [7, 7, 6, 2]]))

In [164]:
# Compare the two arrays with '>'
arr7>arr8

array([[ True, False,  True,  True],
       [False,  True, False,  True],
       [False, False, False,  True]])

What happens when you compare the arrays with `>`?

In [165]:
# Compare the two arrays with '>='
arr7>=arr8

array([[ True, False,  True,  True],
       [False,  True, False,  True],
       [False, False, False,  True]])

In [170]:
# Find which elements of the first array are greater than 7
np.greater(arr7, 7), arr7>7

(array([[False, False, False, False],
        [False,  True, False,  True],
        [False, False, False, False]]),
 array([[False, False, False, False],
        [False,  True, False,  True],
        [False, False, False, False]]))

In [171]:
# Which parts of each array are equal? (try using '==')
arr7==arr8

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [172]:
# Sort one of the arrays you just created in ascending order
np.sort(arr8)

array([[0, 2, 3, 8],
       [0, 3, 3, 4],
       [2, 6, 7, 7]])

In [177]:
# Sort the indexes of one of the arrays you just created
np.sort(np.argsort(arr8))

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]], dtype=int64)

In [178]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(arr8)

3

In [180]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(arr8)

3

In [181]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
arr8.argmax(axis=1)

array([1, 2, 0], dtype=int64)

In [182]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
arr8.argmin(axis=0)

array([0, 1, 0, 0], dtype=int64)

In [ ]:
# Create an array of normally distributed random numbers
arr10 = np.random.normal(size=20)

In [ ]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1,100, num=10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.