In [3]:
import numpy as np

In [7]:
a1 = numpy.array([1, 2, 3])

a2 = numpy.random.rand(2, 3, 3)
a2

array([[[0.23549099, 0.93419254, 0.55260276],
        [0.99283022, 0.75123645, 0.16528468],
        [0.93352249, 0.29286947, 0.28297108]],

       [[0.48311547, 0.0503877 , 0.81682807],
        [0.12643672, 0.5044934 , 0.48739628],
        [0.37734387, 0.56286468, 0.61000441]]])

In [9]:
a3 = numpy.random.rand(2, 3, 3)
a3.shape

(2, 3, 3)

In [10]:
a2 * a3

array([[[0.20748174, 0.4109352 , 0.29889897],
        [0.56599504, 0.56086713, 0.0702386 ],
        [0.25659571, 0.19546079, 0.2313092 ]],

       [[0.44322608, 0.00966604, 0.28201812],
        [0.01908832, 0.48088643, 0.34343133],
        [0.11723732, 0.1166933 , 0.08246152]]])

In [11]:
a2.reshape(3, 6)

array([[0.23549099, 0.93419254, 0.55260276, 0.99283022, 0.75123645,
        0.16528468],
       [0.93352249, 0.29286947, 0.28297108, 0.48311547, 0.0503877 ,
        0.81682807],
       [0.12643672, 0.5044934 , 0.48739628, 0.37734387, 0.56286468,
        0.61000441]])

In [12]:
# Transpose
a3.T

array([[[0.8810602 , 0.91743302],
        [0.57008241, 0.15097134],
        [0.27486826, 0.31069095]],

       [[0.43988276, 0.19183334],
        [0.74659201, 0.95320658],
        [0.66739901, 0.20732034]],

       [[0.54089301, 0.34526007],
        [0.4249553 , 0.70462443],
        [0.81743053, 0.13518185]]])