### Sorting arrays in different ways

In [1]:
import numpy as np

In [6]:
random_array = np.random.randint(10,size=(3,5))
a1 = np.array([1,2,3])
random_array, a1

(array([[9, 8, 9, 9, 7],
        [8, 0, 8, 3, 5],
        [4, 0, 6, 5, 2]]),
 array([1, 2, 3]))

In [7]:
np.sort(random_array), np.sort(a1) # sort each axis

(array([[7, 8, 9, 9, 9],
        [0, 3, 5, 8, 8],
        [0, 2, 4, 5, 6]]),
 array([1, 2, 3]))

#### argsort, argmin ... methods are used to find the elements index if they would have been sorted in ascending order.

In [10]:
np.argsort(random_array)

array([[4, 1, 0, 2, 3],
       [1, 3, 4, 0, 2],
       [1, 4, 0, 3, 2]], dtype=int64)

In [15]:
np.argmax(random_array), np.argmin(random_array)

(0, 6)

In [17]:
np.argmax(random_array, axis=1), np.argmin(random_array, axis=1)

(array([0, 0, 2], dtype=int64), array([4, 1, 1], dtype=int64))