In [1]:
import numpy as np

In [2]:
ones = np.ones((2, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [7]:
random_array = np.random.rand(2, 3)
random_array

array([[0.93532889, 0.19186528, 0.69399858],
       [0.97766053, 0.13865311, 0.8353755 ]])

In [13]:
random_array_2 = np.random.randint(0, 10, (2, 3))
random_array_2

array([[2, 1, 1],
       [0, 2, 5]])

In [11]:
random_array_3 = np.random.random((2, 3))
random_array_3

array([[0.36259798, 0.76991373, 0.52596002],
       [0.54543301, 0.39201191, 0.4405062 ]])