### Compare two different numpy arrays in different formats

[numpy docs](https://numpy.org/doc/stable/reference/routines.logic.html)

In [12]:
import numpy as np
import pandas as pd

In [3]:
a1 = np.array([1, 2, 3, 4])
a1

array([1, 2, 3, 4])

In [4]:
a2 = np.array([[1, 2, 3,1.], [4., 2.,5, 6]])
a2

array([[1., 2., 3., 1.],
       [4., 2., 5., 6.]])

In [5]:
a2>a1

array([[False, False, False, False],
       [ True, False,  True,  True]])

In [6]:
a1>a2

array([[False, False, False,  True],
       [False, False, False, False]])

In [7]:
a1 > 3

array([False, False, False,  True])

In [8]:
a1 == a2

array([[ True,  True,  True, False],
       [False,  True, False, False]])

In [10]:
np.array_equiv(a1, a2)
# np.array_equiv doesn't compare values one by one, it compares the shape and values of the arrays

False

In [11]:
np.any(a1 >= a2)

True