In [6]:
import numpy as np
import pandas as pd

In [7]:

mat1 = np.random.randint(0,10, size=(3,3))
mat2 = np.random.randint(0,10, size=(3,3))

mat1, mat2

(array([[0, 0, 4],
        [5, 9, 9],
        [3, 4, 4]]),
 array([[1, 0, 6],
        [4, 7, 3],
        [7, 3, 3]]))

In [8]:
mat1 @ mat2

array([[ 28,  12,  12],
       [104,  90,  84],
       [ 47,  40,  42]])

In [9]:
mat1 * mat2

array([[ 0,  0, 24],
       [20, 63, 27],
       [21, 12, 12]])

In [10]:
np.dot(mat1, mat2)

array([[ 28,  12,  12],
       [104,  90,  84],
       [ 47,  40,  42]])

# FOOD SALES


In [12]:

days = ["Mon", "Tue", "Wed", "Thu", "Fri"]
products = ["Milk", "Cheese", "Eggs"]

data = np.random.randint(0, 20, size=(5,3))
data

array([[ 4,  0, 11],
       [ 0,  4, 15],
       [ 0, 16, 11],
       [ 9, 14, 14],
       [16, 12, 17]])

In [14]:
weekly_sales = pd.DataFrame(data, index=days, columns=products)
weekly_sales

Milk  Cheese  Eggs
Mon     4       0    11
Tue     0       4    15
Wed     0      16    11
Thu     9      14    14
Fri    16      12    17

In [15]:
prices = np.array([10, 8, 5])

In [16]:
price_df = pd.DataFrame(prices.reshape(1,3), index=["Price"], columns=products)
price_df

Milk  Cheese  Eggs
Price    10       8     5

In [18]:

total_sales = prices @ data.T
total_sales

array([ 95, 107, 183, 272, 341])

In [19]:

weekly_sales["Total ($)"] = total_sales

In [20]:
weekly_sales

Milk  Cheese  Eggs  Total ($)
Mon     4       0    11         95
Tue     0       4    15        107
Wed     0      16    11        183
Thu     9      14    14        272
Fri    16      12    17        341