In [1]:
import numpy as np

In [7]:
test_array = np.random.randint(0, 10, 10)
test_array

array([6, 7, 9, 8, 1, 7, 4, 6, 7, 9])

In [8]:
np.unique(test_array)

array([1, 4, 6, 7, 8, 9])

In [9]:
a4 = np.random.randint(0,10, size=(2,3,2,4))
a4

array([[[[6, 1, 0, 8],
         [3, 5, 3, 2]],

        [[3, 9, 5, 7],
         [9, 9, 7, 0]],

        [[1, 0, 8, 9],
         [3, 3, 6, 0]]],


       [[[9, 4, 0, 6],
         [9, 9, 9, 2]],

        [[9, 9, 1, 8],
         [3, 9, 1, 6]],

        [[0, 2, 3, 2],
         [3, 3, 9, 7]]]])

In [12]:
a4[:,:,:,:1]

array([[[[6],
         [3]],

        [[3],
         [9]],

        [[1],
         [3]]],


       [[[9],
         [9]],

        [[9],
         [3]],

        [[0],
         [3]]]])

In [13]:
a1 = np.random.randint(0,10, size=(2,3))
a2 = np.random.randint(0,10, size=(3,2))
a1@a2

array([[ 6, 15],
       [18, 41]])

In [15]:
a2@a1

array([[27, 52, 21],
       [ 6,  8,  6],
       [12, 16, 12]])

In [22]:
a3 = np.random.randint(0,10, size=(3))
a5 = np.random.randint(0,10, size=(2,3))
a3,a5,a3*a5


(array([8, 3, 3]),
 array([[7, 1, 7],
        [4, 4, 8]]),
 array([[56,  3, 21],
        [32, 12, 24]]))

In [25]:
np.square(a3), np.add(a5, np.square(a3))

(array([64,  9,  9]),
 array([[71, 10, 16],
        [68, 13, 17]]))